### PR TITLE
fix xvideos

### PR DESCRIPTION
**Pull request by craftwar**

### CODE REVIEW

**Comment by tsaiid** [comment]
Will it be any problem if changing all "var" to "let"? How about the legacy browsers' support?

**Comment by craftwar** [comment]
somewhat like local variable, better coding style. I am not very familiar with js. var will be global in some cases

**Comment by tsaiid** [comment]
I'm not familiar with js, either. XD. 

The basic support of 'let' is Chrome ≥ 41, Firefox ≥ 44.  Tampermonkey requires Chrome ≥ 31, Firefox ≥ 46. Although I don't think there are many people using 31 ≤ Chrome < 41, using 'let' instead of 'var' may encounter some errors while using this script. Do you think it is necessary to do that, rather than only fixing the xvideos problem?

**Comment by craftwar** [comment]
I prefer to do it. There old browsers run on XP only. I don't think any reason people won't upgrade to newer version.

BTW, you don't need test JQuery gets object or not, click() will work or do nothing. That's why I reserve console.log() at end.

**Pull request merged**
